//
//  FirestoreCollection.swift
//  DonationPointMe
//
//  Created by KD Chen on 22/6/18.
//  Copyright © 2018 Quest Payment Systems. All rights reserved.
//

import FirebaseCore
import FirebaseFirestore

typealias GoogleFirestore = Firestore // Use this alias if you don't want to import Firebase everywhere

protocol FirestoreCollection {

    /**
     A unique read-only Firestore key of the document.
     If key is empty when writing back to Firestore, a new key will be auto-generated by Firestore
     and this document will be saved as a new document.
     */
    var key: String { get }
    /**
     The collection name as defined in firesotre console
     */
    static var collectionName: String { get }
    static func collectionPath() -> CollectionReference

    static func documentPath(key: String) -> DocumentReference
}

extension FirestoreCollection {
    static func collectionPath() -> CollectionReference {
        return Firestore.firestore().collection(collectionName)
    }

    static func documentPath(key: String) -> DocumentReference {
        return key.isEmpty ?
            Self.collectionPath().document():
            Self.collectionPath().document(key)
    }
}

