# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxFirestoreExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxFirestoreExample

     pod 'RxSwift'
     pod ‘RxCocoa’
     pod 'Firebase/Core'
     pod 'Firebase/Firestore'

  target 'RxFirestoreExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxFirestoreExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
